version: "2"
services:
  mongodb:
    image: mongo:latest
    container_name: "mongo"
    ports:
        - 27017:27017
  app:
    build: 
      context: .
    container_name: "boilerplate"
    environment:
      MONGO_URI: "mongodb://localhost:27017"
      MONGO_DATABASE: "twitter"
      PORT: "8000"
      JWT_SECRET: "115b66fb-ac68-49b0-8326-773e063844bd"
    ports:
      - 8000:8000
